#!/bin/sh

passFile="$1"

test -z "$WIFI_INTERFACE" && { echo '$WIFI_INTERFACE is undefined'; exit 1; }
! test -f "$passFile" && { echo 'A passphrase file is required'; exit 2; }

killall wpa_supplicant dhcpcd
ip link set $WIFI_INTERFACE up && sleep 2
wpa_supplicant -B -D n180211,wext -i $WIFI_INTERFACE -c "$passFile" && sleep 2
dhcpcd
