#!/bin/sh

# radio browser and player

test ! -f "$RADIODB" && { echo "$RADIODB" is missing; exit 1; }

cat "$RADIODB" \
| vis-menu-formatted 'cut -f 1' -l $(expr $(tput lines) - 1) \
| cut -f 2 \
| xargs mpv
