#!/bin/sh

# fetch and save given feed into the feed cache

test -z "$1" && { echo 'A feed URL argument is required'; exit 2; }
test ! -d "$FEEDCACHE" && { echo '$FEEDCACHE must be a valid dir'; exit 1; }

curl "$1" | sfeed > "$FEEDCACHE/$(echo "$1" | sed s:/:___:g)"
